#version du docker-compose
version: '3'
#définition des services
services: 
  database: #le service database
    build:
      context: ./database #pour le build à partir de son Dockerfile
    ports:
      - "5432:5432"
    environment: 
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./databasa/data:/var/lib/postgresql/data/pgdata

  php-fpm:
    build:
      context: ./php-fpm #pour le build à partir de son Dockerfile
    depends_on: #attend que le container database est lancé pour lancer ce container
      - database
    environment: #définition des variables
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
    volumes:
      - ../src:/var/www

  nginx:
    build:
      context: ./nginx #pour le build à partir de son Dockerfile
    volumes:
      - ../src:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./logs:/var/log
    depends_on: #attend que le container php-fpm est lancé pour lancer ce container
      - php-fpm
    ports:
      - "80:80"