#utilisation de l'image officielle de MariaDB
FROM postgres:latest
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD 1234
#Expose le port 5432 pour la connexion à la base de données
EXPOSE 5432




